# Generated by Django 2.0.7 on 2018-08-01 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('appid', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combine_id', models.CharField(max_length=100, null=True)),
                ('union_id', models.CharField(max_length=100, null=True, unique=True)),
                ('open_id', models.CharField(max_length=100, null=True, unique=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('phone', models.CharField(max_length=11, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singn_code', models.CharField(max_length=100, null=True, unique=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('commission', models.IntegerField(default='0', null=True)),
                ('singn_longityde', models.CharField(max_length=100, null=True)),
                ('singn_latitude', models.CharField(max_length=100, null=True)),
                ('img', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=32)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='model.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100, null=True)),
                ('method', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=32)),
                ('visible', models.BooleanField(default=1)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface', to='model.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_id', models.CharField(max_length=100, null=True, unique=True)),
                ('open_id', models.CharField(max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('merchant_code', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=11, null=True, unique=True)),
                ('sex', models.CharField(max_length=7, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
                ('id_code', models.CharField(max_length=100, null=True)),
                ('id_img', models.CharField(max_length=100, null=True)),
                ('head_img', models.CharField(max_length=100, null=True)),
                ('work_longitude', models.CharField(max_length=100, null=True)),
                ('work_latiude', models.CharField(max_length=100, null=True)),
                ('pwd_err_count', models.IntegerField(default='0', null=True)),
                ('pwd_frozen_time', models.DateTimeField(max_length=100, null=True)),
                ('qrcode', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=32)),
                ('visible', models.BooleanField(default=1)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='model.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('logo', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=128)),
                ('iba_loan_name', models.CharField(max_length=128)),
                ('iba_loan_no', models.CharField(max_length=32)),
                ('iba_collection_name', models.CharField(max_length=128)),
                ('iba_collection_no', models.CharField(max_length=32)),
                ('iba_pre_deposit_name', models.CharField(max_length=128)),
                ('iba_pre_deposit_no', models.CharField(max_length=128)),
                ('org_no', models.CharField(max_length=32)),
                ('production', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=32)),
                ('area_code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=250)),
                ('operate_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=32)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='model.Business')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('sex', models.CharField(max_length=7, null=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200, null=True)),
                ('avatar', models.CharField(max_length=200, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('wechat', models.CharField(max_length=100, null=True)),
                ('qq', models.CharField(max_length=20, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=32)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Merchant')),
                ('roles', models.ManyToManyField(to='model.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='role',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='role',
            name='interface',
            field=models.ManyToManyField(to='model.Interface'),
        ),
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(to='model.Menu'),
        ),
        migrations.AddField(
            model_name='role',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Merchant'),
        ),
        migrations.AddField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='menu',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='manager',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='interface',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='domain',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='domain',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='model.Merchant'),
        ),
        migrations.AddField(
            model_name='contract',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Manager'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='business',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.User'),
        ),
        migrations.AddField(
            model_name='business',
            name='merchant',
            field=models.ManyToManyField(related_name='business', to='model.Merchant'),
        ),
    ]
