# Generated by Django 2.0.7 on 2018-08-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20180802_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelphone',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
