# Generated by Django 2.0.7 on 2018-08-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20180802_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
