version: "3"

services:
  fraud-api:
    build: .
    working_dir: /srv
    environment:
      - SERVICE_NAME=fraud_api
      - ZK_SERVERS=111.230.231.89:2181,111.230.231.89:2182
      - ZK_USER=xwfintech
      - ZK_PASS=xxw2018
      - MONGO_URL=mongodb://xwfintech:xxw2018@111.230.231.89:27017/fraud
      - MONGO_USER=xwfintech
      - MONGO_PASS=xxw2018
      - IP=192.168.1.192
      - PORT=10120
      - SENTRY_DSN=http://abba106a336c4117950eef7fbf720577:829bc03e9e4348c98302ab534127121e@111.230.231.89:9000/10
    volumes:
      - ".:/srv"
    command: gunicorn src.main:app -b 0.0.0.0:5000 -k meinheld.gmeinheld.MeinheldWorker
    ports:
      - "10120:5000"